######################################################################
# Automatically generated by qmake (2.01a) Thu Sep 29 15:11:56 2011
######################################################################

CONFIG += opengl
QT += opengl
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
LIBS += -lGL -lGLU

# Input
HEADERS += inputgen.h inputview.h
SOURCES += inputgen.cpp inputview.cpp main.cpp
